# Fix colors
set -as terminal-features ",xterm*:RGB"

# Neovim :checkhealth told me to set these. I have no idea what they do!
set-option -sg escape-time 10
set-option -g focus-events on

# Enable copying over OSC 52
# Read this https://github.com/tmux/tmux/wiki/Clipboard
set -g set-clipboard on
set -g allow-passthrough on
set -as terminal-features ',xterm*:clipboard'

# Start counting from 1
set -g base-index 1

# When a window is closed, re-calculating the numbers
set -g renumber-windows on

# Use Vim keys for switching panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with shift + Vim key
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# kill panes and sessions
unbind x
bind x kill-pane
bind X kill-session

set-option -g status-position top

# Use Neovim keys for moving and copying
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

# TPM plugins
set -g @plugin "tmux-plugins/tpm"
# Catppuccin Status Bar
set -g @plugin "catppuccin/tmux"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"
set -g status-justify "absolute-centre"

set -g status-right-length 100
set -g status-left-length 100

# left status bar
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# left status bar
set -g status-right ""

# windows
set -wg automatic-rename on
set -g automatic-rename-format "Window"
set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
